---
- name: Setup Golang Application on a Virtual Machine
  hosts: "{{ host }}"
  ansible_ssh_pipelining: true

  vars_files:
    - vars.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - include_tasks: tasks/create_user.yml

    - include_tasks: tasks/setup_database.yml

    - include_tasks: tasks/clone-repo.yml

    - include_tasks: tasks/firewall.yml

    - include_tasks: tasks/setup_app.yml

    - include_tasks: tasks/setup_proxy.yml
