---
- name: Setup Golang Application on a Virtual Machine
  hosts: hng

  vars_files:
    - vars.yml

  handlers:
    - import_tasks: handlers/main.yml
     
  tasks:
    - include_tasks: tasks/user.yml

    - include_tasks: tasks/database.yml

    - include_tasks: tasks/clone-repo.yml

    - include_tasks: tasks/app.yml
    
    - include_tasks: tasks/proxy.yml

