---
- name: Clone the golang project repo
  git: 
    repo: "{{ app_repo }}"
    dest: /opt/stage_5b
    single_branch: yes
    version: devops
    force: yes
    update: yes
  become_user: hng

- name: Change file ownership, group and permissions
  file:
    path: /opt/stage_5b
    state: directory
    recurse: true
    owner: hng
    group: hng
    mode: '0755'
  
- name: Switch to the golang app directory
  command: chdir=/opt/stage_5b ls

- name: copy .env file to the app directory
  copy:
    src: ./templates/env
    dest: /opt/stage_5b/.env