---
- name: Install prerequisites for Nginx 1.26
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    state: present
    update_cache: yes

- name: Import the official NGINX signing key
  shell: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor -o /usr/share/keyrings/nginx-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/nginx-archive-keyring.gpg

- name: Verify the downloaded key
  shell: gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg

- name: Set up the apt repository for stable NGINX packages
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list

- name: Set up repository pinning for NGINX packages
  copy:
    content: |
      Package: *
      Pin: origin nginx.org
      Pin: release o=nginx
      Pin-Priority: 900
    dest: /etc/apt/preferences.d/99nginx

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install NGINX Open Source
  apt:
    name: nginx=1.26.*
    state: present

- name: Start NGINX
  service:
    name: nginx
    state: started

- name: Verify NGINX is running
  command: curl -I 127.0.0.1
  register: nginx_status

- name: Display NGINX status
  debug:
    msg: "{{ nginx_status.stdout }}"


- name: Configure Nginx as a reverse proxy
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Test Nginx configuration
  shell: nginx -t
  notify: Restart Nginx
