---
- name: Ensure temporary directory exists
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Install dependencies for building Nginx
  apt:
    name:
      - build-essential
      - libpcre3
      - libpcre3-dev
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - wget
    state: present
    update_cache: yes

- name: Download Nginx source tarball
  get_url:
    url: "{{ nginx_url }}"
    dest: "{{ temp_dir }}/nginx-{{ nginx_version }}.tar.gz"

- name: Extract Nginx source tarball
  unarchive:
    src: "{{ temp_dir }}/nginx-{{ nginx_version }}.tar.gz"
    dest: "{{ temp_dir }}"
    remote_src: yes

- name: Configure Nginx
  shell: |
    ./configure --prefix={{ nginx_install_dir }} --with-http_ssl_module
  args:
    chdir: "{{ temp_dir }}/nginx-{{ nginx_version }}"

- name: Build and install Nginx
  shell: |
    make && make install
  args:
    chdir: "{{ temp_dir }}/nginx-{{ nginx_version }}"

- name: Create Nginx directories
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: Create symlink for sites-enabled
  file:
    src: /etc/nginx/sites-available
    dest: /etc/nginx/sites-enabled
    state: link

- name: Create Nginx systemd service file
  copy:
    dest: /etc/systemd/system/nginx.service
    content: |
      [Unit]
      Description=The NGINX HTTP and reverse proxy server
      After=network.target

      [Service]
      ExecStart={{ nginx_install_dir }}/sbin/nginx
      ExecReload=/bin/kill -s HUP $MAINPID
      ExecStop=/bin/kill -s QUIT $MAINPID
      PIDFile={{ nginx_install_dir }}/logs/nginx.pid
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd to recognize new nginx service
  systemd:
    daemon_reload: yes

- name: Enable and start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx as a reverse proxy
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: hng
    group: hng
    mode: '0644'

- name: Test Nginx configuration
  shell: "{{ nginx_install_dir }}/sbin/nginx -t"
  notify: Restart Nginx
